#!/bin/sh
mkdir run
mkdir run/zk
mkdir run/mm{1,2,3}   # mesos-master workdir
mkdir run/mm{1,2,3}l  # mesos-master logs
mkdir run/ms{1,2,3}   # mesos-slave workdir (incuding children logs)
mkdir run/ms{1,2,3}l  # mesos-slave logs

